{"date":"2019-11-01T12:03:58.527","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:03:58.551","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:02.163","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:02.175","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:05.986","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:05.988","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:10.204","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:10.222","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:14.877","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:15.159","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:18.168","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'uecirculate接收转账操作失败: { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T12:04:18.169","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"8620","data":'this error from transfer2Pog(),the error trace is O% { Error: assertion failure with message: cannot transfer to self
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 500,
     message: 'Internal Service Error',
     error:
      { code: 3050003,
        name: 'eosio_assert_message_exception',
        what: 'eosio_assert_message assertion failure',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:28.456","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'11g22p33s接收转账操作失败: { Error: duplicate transaction 74d37edcc6c72d751f4f020f61c64daf89f2418122b34857b827becc5a9fd13b
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:28.471","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'this error from transfer2Pog(),the error trace is O% { Error: duplicate transaction 74d37edcc6c72d751f4f020f61c64daf89f2418122b34857b827becc5a9fd13b
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:30.265","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'11g22p33s接收转账操作失败: { Error: duplicate transaction 01206c2a8de211e7f31e915e3bca62468b574cbef758b7ee6b9600adb4c89676
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:30.267","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'this error from transfer2Pog(),the error trace is O% { Error: duplicate transaction 01206c2a8de211e7f31e915e3bca62468b574cbef758b7ee6b9600adb4c89676
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:30.425","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'11g22p33s接收转账操作失败: { Error: duplicate transaction 01206c2a8de211e7f31e915e3bca62468b574cbef758b7ee6b9600adb4c89676
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
{"date":"2019-11-01T20:00:30.427","level":"ERROR","category":"transfer2Pog.js","host":"frank-hp","pid":"3660","data":'this error from transfer2Pog(),the error trace is O% { Error: duplicate transaction 01206c2a8de211e7f31e915e3bca62468b574cbef758b7ee6b9600adb4c89676
    at new RpcError (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-rpcerror.js:26:28)
    at JsonRpc.<anonymous> (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:118:35)
    at step (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:36:23)
    at Object.next (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:17:53)
    at fulfilled (D:\work_space\yuezhi\eos\exchange\node_modules\eosjs\dist\eosjs-jsonrpc.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }'}
